# Generated by Django 5.0.6 on 2024-06-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("detect", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pest",
            old_name="pest_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="pest",
            name="prevention_method",
        ),
        migrations.AddField(
            model_name="pest",
            name="prevention_methods",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pestdetection",
            name="confidence",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="pest",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pestdetection",
            name="image",
            field=models.ImageField(upload_to="pest_detections/"),
        ),
    ]
