# Generated by Django 5.0.6 on 2024-06-29 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("detect", "0002_rename_pest_name_pest_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="pestdetection",
            name="pest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detections",
                to="detect.pest",
            ),
        ),
        migrations.AlterField(
            model_name="pestdetection",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pest_detections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
