# Generated by Django 5.0.6 on 2024-07-01 06:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("selfchatbot", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ChatMessage",
            new_name="Chatbot",
        ),
    ]
