# Generated by Django 5.0.6 on 2024-07-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("selfchatbot", "0002_rename_chatmessage_chatbot"),
    ]

    operations = [
        migrations.CreateModel(
            name="Database",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="question")),
                ("answer", models.TextField(verbose_name="answer")),
            ],
        ),
    ]
