# Generated by Django 5.0.6 on 2024-07-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("selfchatbot", "0003_database"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbot",
            name="session_id",
            field=models.CharField(max_length=32),
        ),
    ]
